/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamPerformanceRouteImport } from './routes/_authenticated/team-performance'
import { Route as AuthenticatedTeamMembersRouteImport } from './routes/_authenticated/team-members'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMonthlyTargetsRouteImport } from './routes/_authenticated/monthly-targets'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKpiRouteImport } from './routes/_authenticated/kpi'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingCyclesRouteImport } from './routes/_authenticated/billing-cycles'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated/batches'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamPerformanceRoute =
  AuthenticatedTeamPerformanceRouteImport.update({
    id: '/team-performance',
    path: '/team-performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamMembersRoute =
  AuthenticatedTeamMembersRouteImport.update({
    id: '/team-members',
    path: '/team-members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonthlyTargetsRoute =
  AuthenticatedMonthlyTargetsRouteImport.update({
    id: '/monthly-targets',
    path: '/monthly-targets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKpiRoute = AuthenticatedKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingCyclesRoute =
  AuthenticatedBillingCyclesRouteImport.update({
    id: '/billing-cycles',
    path: '/billing-cycles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/billing-cycles': typeof AuthenticatedBillingCyclesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/monthly-targets': typeof AuthenticatedMonthlyTargetsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/team-members': typeof AuthenticatedTeamMembersRoute
  '/team-performance': typeof AuthenticatedTeamPerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/billing-cycles': typeof AuthenticatedBillingCyclesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/monthly-targets': typeof AuthenticatedMonthlyTargetsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/team-members': typeof AuthenticatedTeamMembersRoute
  '/team-performance': typeof AuthenticatedTeamPerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRoute
  '/_authenticated/billing-cycles': typeof AuthenticatedBillingCyclesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kpi': typeof AuthenticatedKpiRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/monthly-targets': typeof AuthenticatedMonthlyTargetsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/_authenticated/team-members': typeof AuthenticatedTeamMembersRoute
  '/_authenticated/team-performance': typeof AuthenticatedTeamPerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/batches'
    | '/billing-cycles'
    | '/dashboard'
    | '/kpi'
    | '/leads'
    | '/monthly-targets'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/targets'
    | '/team-members'
    | '/team-performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/batches'
    | '/billing-cycles'
    | '/dashboard'
    | '/kpi'
    | '/leads'
    | '/monthly-targets'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/targets'
    | '/team-members'
    | '/team-performance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/batches'
    | '/_authenticated/billing-cycles'
    | '/_authenticated/dashboard'
    | '/_authenticated/kpi'
    | '/_authenticated/leads'
    | '/_authenticated/monthly-targets'
    | '/_authenticated/reports'
    | '/_authenticated/revenue'
    | '/_authenticated/settings'
    | '/_authenticated/targets'
    | '/_authenticated/team-members'
    | '/_authenticated/team-performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-performance': {
      id: '/_authenticated/team-performance'
      path: '/team-performance'
      fullPath: '/team-performance'
      preLoaderRoute: typeof AuthenticatedTeamPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team-members': {
      id: '/_authenticated/team-members'
      path: '/team-members'
      fullPath: '/team-members'
      preLoaderRoute: typeof AuthenticatedTeamMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monthly-targets': {
      id: '/_authenticated/monthly-targets'
      path: '/monthly-targets'
      fullPath: '/monthly-targets'
      preLoaderRoute: typeof AuthenticatedMonthlyTargetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kpi': {
      id: '/_authenticated/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof AuthenticatedKpiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing-cycles': {
      id: '/_authenticated/billing-cycles'
      path: '/billing-cycles'
      fullPath: '/billing-cycles'
      preLoaderRoute: typeof AuthenticatedBillingCyclesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRoute
  AuthenticatedBillingCyclesRoute: typeof AuthenticatedBillingCyclesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKpiRoute: typeof AuthenticatedKpiRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMonthlyTargetsRoute: typeof AuthenticatedMonthlyTargetsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
  AuthenticatedTeamMembersRoute: typeof AuthenticatedTeamMembersRoute
  AuthenticatedTeamPerformanceRoute: typeof AuthenticatedTeamPerformanceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBatchesRoute: AuthenticatedBatchesRoute,
  AuthenticatedBillingCyclesRoute: AuthenticatedBillingCyclesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKpiRoute: AuthenticatedKpiRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMonthlyTargetsRoute: AuthenticatedMonthlyTargetsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
  AuthenticatedTeamMembersRoute: AuthenticatedTeamMembersRoute,
  AuthenticatedTeamPerformanceRoute: AuthenticatedTeamPerformanceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
